# Generated by Django 4.1.5 on 2023-01-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('releaseYear', models.IntegerField()),
                ('genre', models.CharField(max_length=32)),
                ('rating', models.FloatField()),
                ('runningTime', models.IntegerField()),
                ('review', models.TextField()),
                ('director', models.CharField(max_length=32)),
                ('actor', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
